
CREATE VIEW KEYWORD_SEARCH AS
SELECT audio_file_id FROM keywords
WHERE 'Jewish' = ANY(keyword);
SELECT * FROM KEYWORD_SEARCH;
SELECT * FROM (KEYWORD_SEARCH NATURAL JOIN AUDIO_FILE);

CREATE VIEW INTERVIEWER_SEARCH AS
SELECT INTERVIEWER_ID FROM INTERVIEWER
WHERE NAME = 'Wyatt Henry';
CREATE VIEW INTERVIEWER_AUDIO AS
SELECT AUDIO_FILE_ID FROM (INTERVIEWER_SEARCH NATURAL JOIN INTERVIEWED_BY);
SELECT * FROM (INTERVIEWER_AUDIO NATURAL JOIN AUDIO_FILE);

CREATE VIEW INTERVIEWEE_SEARCH AS
SElECT INTERVIEWEE_ID FROM INTERVIEWEE
WHERE NAME = 'Herman "Humpsy" Finkle';
CREATE VIEW INTERVIEWEE_AUDIO AS
SELECT AUDIO_FILE_ID FROM (INTERVIEWEE_SEARCH NATURAL JOIN INTERVIEW_OF);
SELECT * FROM (INTERVIEWEE_AUDIO NATURAL JOIN AUDIO_FILE);

CREATE VIEW RACE_SEARCH AS
SELECT INTERVIEWEE_ID FROM INTERVIEWEE_RACES
WHERE RACE = 'white';
CREATE VIEW INTERVIEWEE_RACE_AUDIO AS
SELECT AUDIO_FILE_ID FROM (RACE_SEARCH NATURAL JOIN INTERVIEW_OF);
SELECT * FROM (INTERVIEWEE_RACE_AUDIO NATURAL JOIN AUDIO_FILE);

CREATE VIEW CITY_SEARCH AS
SELECT INTERVIEWEE_ID FROM INTERVIEWEE      
WHERE CITY = 'Trenton';
CREATE VIEW INTERVIEWEE_CITY_AUDIO AS
SELECT AUDIO_FILE_ID FROM (CITY_SEARCH NATURAL JOIN INTERVIEW_OF);
SELECT * FROM (INTERVIEWEE_CITY_AUDIO NATURAL JOIN AUDIO_FILE);

CREATE VIEW MD_EDIT AS
SELECT REPORT_NUM, USR_EMAIL FROM REPORT
WHERE type = 'md_edit';
SELECT * FROM (MD_EDIT NATURAL JOIN METADATA_EDIT_REQUEST);

CREATE VIEW BLOCKED_USR AS
SELECT USR_EMAIL,USR_USERNAME FROM USR
WHERE IS_BLOCKED = 'Y';
SELECT * FROM (BLOCKED_USR NATURAL JOIN BLOCK);

DELETE FROM METADATA_EDIT_REQUEST WHERE REPORT_NUM = 1;
DELETE FROM REPORT WHERE REPORT_NUM = 1;





